//
// Body1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Body1: Codable {

    public var contentType: String?
    public var contentDisposition: String?
    public var headers: [String:[String]]?
    public var length: Int64?
    public var name: String?
    public var fileName: String?

    public init(contentType: String?, contentDisposition: String?, headers: [String:[String]]?, length: Int64?, name: String?, fileName: String?) {
        self.contentType = contentType
        self.contentDisposition = contentDisposition
        self.headers = headers
        self.length = length
        self.name = name
        self.fileName = fileName
    }

    public enum CodingKeys: String, CodingKey { 
        case contentType = "ContentType"
        case contentDisposition = "ContentDisposition"
        case headers = "Headers"
        case length = "Length"
        case name = "Name"
        case fileName = "FileName"
    }

}

