//
// CreateFileViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateFileViewModel: Codable {

    public var name: String
    public var category: String?
    public var _description: String?

    public init(name: String, category: String?, _description: String?) {
        self.name = name
        self.category = category
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case category
        case _description = "description"
    }

}

