//
// FileViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FileViewModel: Codable {

    public var profileId: String?
    public var _id: String?
    public var size: Int64?
    public var uploaded: Bool?
    public var createdAt: Date?
    public var modifiedAt: Date?
    public var fileName: String?
    public var mimeType: String?
    public var name: String
    public var category: String?
    public var _description: String?

    public init(profileId: String?, _id: String?, size: Int64?, uploaded: Bool?, createdAt: Date?, modifiedAt: Date?, fileName: String?, mimeType: String?, name: String, category: String?, _description: String?) {
        self.profileId = profileId
        self._id = _id
        self.size = size
        self.uploaded = uploaded
        self.createdAt = createdAt
        self.modifiedAt = modifiedAt
        self.fileName = fileName
        self.mimeType = mimeType
        self.name = name
        self.category = category
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case profileId
        case _id = "id"
        case size
        case uploaded
        case createdAt
        case modifiedAt
        case fileName
        case mimeType
        case name
        case category
        case _description = "description"
    }

}

