//
// ScopeViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ScopeViewModel: Codable {

    public var name: String
    public var _description: String?
    public var enabled: Bool?

    public init(name: String, _description: String?, enabled: Bool?) {
        self.name = name
        self._description = _description
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _description = "description"
        case enabled
    }

}

