//
// StoryProfileDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StoryProfileDTO: Codable {

    public var email: String?
    public var emailVerified: Bool?
    public var phone: String?
    public var phoneVerified: Bool?
    public var username: String?

    public init(email: String?, emailVerified: Bool?, phone: String?, phoneVerified: Bool?, username: String?) {
        self.email = email
        self.emailVerified = emailVerified
        self.phone = phone
        self.phoneVerified = phoneVerified
        self.username = username
    }


}

