//
// StoryDemographics.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StoryDemographics: Codable {

    public var profileId: String?
    public var modifiedAt: Date?
    public var modifiedBy: String?
    public var verified: Bool?
    public var verifiedAt: Date?
    public var verifiedBy: String?
    public var name: String?
    public var surname: String?
    public var patronymic: String?
    public var gender: Bool?
    public var birthday: Date?

    public init(profileId: String?, modifiedAt: Date?, modifiedBy: String?, verified: Bool?, verifiedAt: Date?, verifiedBy: String?, name: String?, surname: String?, patronymic: String?, gender: Bool?, birthday: Date?) {
        self.profileId = profileId
        self.modifiedAt = modifiedAt
        self.modifiedBy = modifiedBy
        self.verified = verified
        self.verifiedAt = verifiedAt
        self.verifiedBy = verifiedBy
        self.name = name
        self.surname = surname
        self.patronymic = patronymic
        self.gender = gender
        self.birthday = birthday
    }


}

