//
// StoryITNDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StoryITNDTO: Codable {

    public var itn: String?

    public init(itn: String?) {
        self.itn = itn
    }


}

