//
// StoryBankAccountDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StoryBankAccountDTO: Codable {

    public var name: String
    public var _description: String?
    public var settlementAccount: String?
    public var bank: String?
    public var bic: String?
    public var correspondentAccount: String?

    public init(name: String, _description: String?, settlementAccount: String?, bank: String?, bic: String?, correspondentAccount: String?) {
        self.name = name
        self._description = _description
        self.settlementAccount = settlementAccount
        self.bank = bank
        self.bic = bic
        self.correspondentAccount = correspondentAccount
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _description = "description"
        case settlementAccount
        case bank
        case bic
        case correspondentAccount
    }

}

