//
// StorySNILSDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StorySNILSDTO: Codable {

    public var snils: String?

    public init(snils: String?) {
        self.snils = snils
    }


}

