//
// StoryBankAccount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StoryBankAccount: Codable {

    public var profileId: String?
    public var _id: String?
    public var modifiedAt: Date?
    public var modifiedBy: String?
    public var verified: Bool?
    public var verifiedAt: Date?
    public var verifiedBy: String?
    public var name: String
    public var _description: String?
    public var settlementAccount: String?
    public var bank: String?
    public var bic: String?
    public var correspondentAccount: String?

    public init(profileId: String?, _id: String?, modifiedAt: Date?, modifiedBy: String?, verified: Bool?, verifiedAt: Date?, verifiedBy: String?, name: String, _description: String?, settlementAccount: String?, bank: String?, bic: String?, correspondentAccount: String?) {
        self.profileId = profileId
        self._id = _id
        self.modifiedAt = modifiedAt
        self.modifiedBy = modifiedBy
        self.verified = verified
        self.verifiedAt = verifiedAt
        self.verifiedBy = verifiedBy
        self.name = name
        self._description = _description
        self.settlementAccount = settlementAccount
        self.bank = bank
        self.bic = bic
        self.correspondentAccount = correspondentAccount
    }

    public enum CodingKeys: String, CodingKey { 
        case profileId
        case _id = "id"
        case modifiedAt
        case modifiedBy
        case verified
        case verifiedAt
        case verifiedBy
        case name
        case _description = "description"
        case settlementAccount
        case bank
        case bic
        case correspondentAccount
    }

}

