//
// StoryPasportDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StoryPasportDTO: Codable {

    public var sn: String?
    public var issuedBy: String?
    public var issuedAt: Date?
    public var code: String?
    public var pages: [StoryPasportPageViewModel]?

    public init(sn: String?, issuedBy: String?, issuedAt: Date?, code: String?, pages: [StoryPasportPageViewModel]?) {
        self.sn = sn
        self.issuedBy = issuedBy
        self.issuedAt = issuedAt
        self.code = code
        self.pages = pages
    }


}

