//
// StoryPasport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StoryPasport: Codable {

    public var profileId: String?
    public var modifiedAt: Date?
    public var modifiedBy: String?
    public var verified: Bool?
    public var verifiedAt: Date?
    public var verifiedBy: String?
    public var sn: String?
    public var issuedBy: String?
    public var issuedAt: Date?
    public var code: String?
    public var pages: [StoryPasportPageViewModel]?

    public init(profileId: String?, modifiedAt: Date?, modifiedBy: String?, verified: Bool?, verifiedAt: Date?, verifiedBy: String?, sn: String?, issuedBy: String?, issuedAt: Date?, code: String?, pages: [StoryPasportPageViewModel]?) {
        self.profileId = profileId
        self.modifiedAt = modifiedAt
        self.modifiedBy = modifiedBy
        self.verified = verified
        self.verifiedAt = verifiedAt
        self.verifiedBy = verifiedBy
        self.sn = sn
        self.issuedBy = issuedBy
        self.issuedAt = issuedAt
        self.code = code
        self.pages = pages
    }


}

