//
// StoryProfile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StoryProfile: Codable {

    public var _id: String?
    public var createdAt: Date?
    public var createdBy: String?
    public var modifiedAt: Date?
    public var modifiedBy: String?
    public var email: String?
    public var emailVerified: Bool?
    public var phone: String?
    public var phoneVerified: Bool?
    public var username: String?

    public init(_id: String?, createdAt: Date?, createdBy: String?, modifiedAt: Date?, modifiedBy: String?, email: String?, emailVerified: Bool?, phone: String?, phoneVerified: Bool?, username: String?) {
        self._id = _id
        self.createdAt = createdAt
        self.createdBy = createdBy
        self.modifiedAt = modifiedAt
        self.modifiedBy = modifiedBy
        self.email = email
        self.emailVerified = emailVerified
        self.phone = phone
        self.phoneVerified = phoneVerified
        self.username = username
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case createdAt
        case createdBy
        case modifiedAt
        case modifiedBy
        case email
        case emailVerified
        case phone
        case phoneVerified
        case username
    }

}

