//
// StoryDemographicsDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StoryDemographicsDTO: Codable {

    public var name: String?
    public var surname: String?
    public var patronymic: String?
    public var gender: Bool?
    public var birthday: Date?

    public init(name: String?, surname: String?, patronymic: String?, gender: Bool?, birthday: Date?) {
        self.name = name
        self.surname = surname
        self.patronymic = patronymic
        self.gender = gender
        self.birthday = birthday
    }


}

