//
// StorySNILS.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StorySNILS: Codable {

    public var profileId: String?
    public var modifiedAt: Date?
    public var modifiedBy: String?
    public var verified: Bool?
    public var verifiedAt: Date?
    public var verifiedBy: String?
    public var size: Int64?
    public var mimeType: String?
    public var snils: String?

    public init(profileId: String?, modifiedAt: Date?, modifiedBy: String?, verified: Bool?, verifiedAt: Date?, verifiedBy: String?, size: Int64?, mimeType: String?, snils: String?) {
        self.profileId = profileId
        self.modifiedAt = modifiedAt
        self.modifiedBy = modifiedBy
        self.verified = verified
        self.verifiedAt = verifiedAt
        self.verifiedBy = verifiedBy
        self.size = size
        self.mimeType = mimeType
        self.snils = snils
    }


}

