//
// VerifyPhoneResultViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VerifyPhoneResultViewModel: Codable {

    public var expiration: Date
    public var signature: String

    public init(expiration: Date, signature: String) {
        self.expiration = expiration
        self.signature = signature
    }


}

