
platform :ios, '11.0'

use_frameworks!

workspace 'StoryID'

target 'StoryID' do
  pod 'Alamofire', '~> 4.8'
  pod 'AlamofireImage', '~> 3.5'
  pod 'p2.OAuth2', '~> 5.0'
  pod 'CryptoSwift', '~> 1.3'

end
