platform :ios, '11.0'

use_frameworks!

workspace 'StoryID'

target 'StoryID' do
  pod 'Alamofire', '~> 4.9'
  pod 'AlamofireImage', '~> 3.5'
  pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2.git', :submodules => true, :tag => '5.3.0'
  pod 'CryptoSwift', '~> 1.3'
end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
