platform :ios, '12.1'

use_frameworks!

workspace 'StoryID'

target 'StoryID' do
  pod 'Alamofire', '~> 4.9'
  pod 'AlamofireImage', '~> 3.5'
  pod 'p2.OAuth2', '~> 5.3'
  pod 'CryptoSwift', '~> 1.3'
end
