//
// ApplicationUsersAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ApplicationUsersAPI {
    /**
     Получение списка пользователя приложения

     - parameter client: (query) Название клиента 
     - parameter lient: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listApplicationUsers(client: String, lient: String, completion: @escaping ((_ data: [StoryAppUser]?,_ error: Error?) -> Void)) {
        listApplicationUsersWithRequestBuilder(client: client, lient: lient).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Получение списка пользователя приложения
     - GET /ApplicationUsers/{сlient}
     - 

     - examples: [{contentType=application/json, example=[ {
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "blockDescription" : "blockDescription",
  "blocked" : true,
  "createdBy" : "createdBy",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "appId" : "appId",
  "blockedUntil" : "2000-01-23T04:56:07.000+00:00",
  "blockedAt" : "2000-01-23T04:56:07.000+00:00",
  "modifiedBy" : "modifiedBy",
  "blockedBy" : "blockedBy",
  "id" : "id",
  "userId" : "userId"
}, {
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "blockDescription" : "blockDescription",
  "blocked" : true,
  "createdBy" : "createdBy",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "appId" : "appId",
  "blockedUntil" : "2000-01-23T04:56:07.000+00:00",
  "blockedAt" : "2000-01-23T04:56:07.000+00:00",
  "modifiedBy" : "modifiedBy",
  "blockedBy" : "blockedBy",
  "id" : "id",
  "userId" : "userId"
} ]}]
     - parameter client: (query) Название клиента 
     - parameter lient: (path)  

     - returns: RequestBuilder<[StoryAppUser]> 
     */
    open class func listApplicationUsersWithRequestBuilder(client: String, lient: String) -> RequestBuilder<[StoryAppUser]> {
        var path = "/ApplicationUsers/{сlient}"
        let lientPreEscape = "\(lient)"
        let lientPostEscape = lientPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{сlient}", with: lientPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "client": client
        ])

        let requestBuilder: RequestBuilder<[StoryAppUser]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Добавление пользоваетля в приложение через клиент

     - parameter client: (path) Идентификатор клиента 
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func setApplicationUsers(client: String, body: AppUserDTO? = nil, completion: @escaping ((_ data: StoryAppUser?,_ error: Error?) -> Void)) {
        setApplicationUsersWithRequestBuilder(client: client, body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Добавление пользоваетля в приложение через клиент
     - PUT /ApplicationUsers/{client}
     - 

     - examples: [{contentType=application/json, example={
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "blockDescription" : "blockDescription",
  "blocked" : true,
  "createdBy" : "createdBy",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "appId" : "appId",
  "blockedUntil" : "2000-01-23T04:56:07.000+00:00",
  "blockedAt" : "2000-01-23T04:56:07.000+00:00",
  "modifiedBy" : "modifiedBy",
  "blockedBy" : "blockedBy",
  "id" : "id",
  "userId" : "userId"
}}]
     - parameter client: (path) Идентификатор клиента 
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<StoryAppUser> 
     */
    open class func setApplicationUsersWithRequestBuilder(client: String, body: AppUserDTO? = nil) -> RequestBuilder<StoryAppUser> {
        var path = "/ApplicationUsers/{client}"
        let clientPreEscape = "\(client)"
        let clientPostEscape = clientPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{client}", with: clientPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryAppUser>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
