//
// BankAccountsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class BankAccountsAPI {
    /**
     Создание банковского счета

     - parameter profileId: (path) Уникальный идентификатор в формате StoryId 
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createBankAccount(profileId: String, body: StoryBankAccountDTO? = nil, completion: @escaping ((_ data: StoryBankAccount?,_ error: Error?) -> Void)) {
        createBankAccountWithRequestBuilder(profileId: profileId, body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Создание банковского счета
     - POST /profiles/{profileId}/bankaccounts

     - examples: [{contentType=application/json, example={
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "verifiedBy" : "verifiedBy",
  "bank" : "bank",
  "profileId" : "profileId",
  "correspondentAccount" : "correspondentAccount",
  "name" : "name",
  "modifiedBy" : "modifiedBy",
  "id" : "id",
  "settlementAccount" : "settlementAccount",
  "bic" : "bic"
}}]
     - parameter profileId: (path) Уникальный идентификатор в формате StoryId 
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<StoryBankAccount> 
     */
    open class func createBankAccountWithRequestBuilder(profileId: String, body: StoryBankAccountDTO? = nil) -> RequestBuilder<StoryBankAccount> {
        var path = "/profiles/{profileId}/bankaccounts"
        let profileIdPreEscape = "\(profileId)"
        let profileIdPostEscape = profileIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{profileId}", with: profileIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryBankAccount>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Удаление банковского счета

     - parameter profileId: (path) Уникальный идентификатор в формате StoryId 
     - parameter _id: (path) Уникальный идентификатор в формате StoryId 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteBankAccountById(profileId: String, _id: String, completion: @escaping ((_ data: StoryBankAccount?,_ error: Error?) -> Void)) {
        deleteBankAccountByIdWithRequestBuilder(profileId: profileId, _id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Удаление банковского счета
     - DELETE /profiles/{profileId}/bankaccounts/{id}

     - examples: [{contentType=application/json, example={
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "verifiedBy" : "verifiedBy",
  "bank" : "bank",
  "profileId" : "profileId",
  "correspondentAccount" : "correspondentAccount",
  "name" : "name",
  "modifiedBy" : "modifiedBy",
  "id" : "id",
  "settlementAccount" : "settlementAccount",
  "bic" : "bic"
}}]
     - parameter profileId: (path) Уникальный идентификатор в формате StoryId 
     - parameter _id: (path) Уникальный идентификатор в формате StoryId 

     - returns: RequestBuilder<StoryBankAccount> 
     */
    open class func deleteBankAccountByIdWithRequestBuilder(profileId: String, _id: String) -> RequestBuilder<StoryBankAccount> {
        var path = "/profiles/{profileId}/bankaccounts/{id}"
        let profileIdPreEscape = "\(profileId)"
        let profileIdPostEscape = profileIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{profileId}", with: profileIdPostEscape, options: .literal, range: nil)
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryBankAccount>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Получение банковского счета

     - parameter profileId: (path) Уникальный идентификатор в формате StoryId 
     - parameter _id: (path) Уникальный идентификатор в формате StoryId 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getBankAccountById(profileId: String, _id: String, completion: @escaping ((_ data: StoryBankAccount?,_ error: Error?) -> Void)) {
        getBankAccountByIdWithRequestBuilder(profileId: profileId, _id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Получение банковского счета
     - GET /profiles/{profileId}/bankaccounts/{id}

     - examples: [{contentType=application/json, example={
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "verifiedBy" : "verifiedBy",
  "bank" : "bank",
  "profileId" : "profileId",
  "correspondentAccount" : "correspondentAccount",
  "name" : "name",
  "modifiedBy" : "modifiedBy",
  "id" : "id",
  "settlementAccount" : "settlementAccount",
  "bic" : "bic"
}}]
     - parameter profileId: (path) Уникальный идентификатор в формате StoryId 
     - parameter _id: (path) Уникальный идентификатор в формате StoryId 

     - returns: RequestBuilder<StoryBankAccount> 
     */
    open class func getBankAccountByIdWithRequestBuilder(profileId: String, _id: String) -> RequestBuilder<StoryBankAccount> {
        var path = "/profiles/{profileId}/bankaccounts/{id}"
        let profileIdPreEscape = "\(profileId)"
        let profileIdPostEscape = profileIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{profileId}", with: profileIdPostEscape, options: .literal, range: nil)
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryBankAccount>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Получение банковского счета

     - parameter profileId: (path) Уникальный идентификатор в формате StoryId 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listBankAccounts(profileId: String, completion: @escaping ((_ data: [StoryBankAccount]?,_ error: Error?) -> Void)) {
        listBankAccountsWithRequestBuilder(profileId: profileId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Получение банковского счета
     - GET /profiles/{profileId}/bankaccounts

     - examples: [{contentType=application/json, example=[ {
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "verifiedBy" : "verifiedBy",
  "bank" : "bank",
  "profileId" : "profileId",
  "correspondentAccount" : "correspondentAccount",
  "name" : "name",
  "modifiedBy" : "modifiedBy",
  "id" : "id",
  "settlementAccount" : "settlementAccount",
  "bic" : "bic"
}, {
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "verifiedBy" : "verifiedBy",
  "bank" : "bank",
  "profileId" : "profileId",
  "correspondentAccount" : "correspondentAccount",
  "name" : "name",
  "modifiedBy" : "modifiedBy",
  "id" : "id",
  "settlementAccount" : "settlementAccount",
  "bic" : "bic"
} ]}]
     - parameter profileId: (path) Уникальный идентификатор в формате StoryId 

     - returns: RequestBuilder<[StoryBankAccount]> 
     */
    open class func listBankAccountsWithRequestBuilder(profileId: String) -> RequestBuilder<[StoryBankAccount]> {
        var path = "/profiles/{profileId}/bankaccounts"
        let profileIdPreEscape = "\(profileId)"
        let profileIdPostEscape = profileIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{profileId}", with: profileIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[StoryBankAccount]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Изменение банковского счета

     - parameter profileId: (path) Уникальный идентификатор в формате StoryId 
     - parameter _id: (path) Уникальный идентификатор в формате StoryId 
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateBankAccount(profileId: String, _id: String, body: StoryBankAccountDTO? = nil, completion: @escaping ((_ data: StoryBankAccount?,_ error: Error?) -> Void)) {
        updateBankAccountWithRequestBuilder(profileId: profileId, _id: _id, body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Изменение банковского счета
     - PUT /profiles/{profileId}/bankaccounts/{id}

     - examples: [{contentType=application/json, example={
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "verifiedBy" : "verifiedBy",
  "bank" : "bank",
  "profileId" : "profileId",
  "correspondentAccount" : "correspondentAccount",
  "name" : "name",
  "modifiedBy" : "modifiedBy",
  "id" : "id",
  "settlementAccount" : "settlementAccount",
  "bic" : "bic"
}}]
     - parameter profileId: (path) Уникальный идентификатор в формате StoryId 
     - parameter _id: (path) Уникальный идентификатор в формате StoryId 
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<StoryBankAccount> 
     */
    open class func updateBankAccountWithRequestBuilder(profileId: String, _id: String, body: StoryBankAccountDTO? = nil) -> RequestBuilder<StoryBankAccount> {
        var path = "/profiles/{profileId}/bankaccounts/{id}"
        let profileIdPreEscape = "\(profileId)"
        let profileIdPostEscape = profileIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{profileId}", with: profileIdPostEscape, options: .literal, range: nil)
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryBankAccount>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Подтверждение банковского счета

     - parameter _id: (path) Уникальный идентификатор в формате StoryId 
     - parameter profileId: (path)  
     - parameter verified: (query)  (optional, default to false)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func verifyBankAccount(_id: String, profileId: String, verified: Bool? = nil, completion: @escaping ((_ data: StoryITN?,_ error: Error?) -> Void)) {
        verifyBankAccountWithRequestBuilder(_id: _id, profileId: profileId, verified: verified).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Подтверждение банковского счета
     - PUT /profiles/{profileId}/bankaccounts/{id}/verify

     - examples: [{contentType=application/json, example={
  "itn" : "itn",
  "size" : 0,
  "profileId" : "profileId",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "modifiedBy" : "modifiedBy",
  "mimeType" : "mimeType",
  "verifiedBy" : "verifiedBy"
}}]
     - parameter _id: (path) Уникальный идентификатор в формате StoryId 
     - parameter profileId: (path)  
     - parameter verified: (query)  (optional, default to false)

     - returns: RequestBuilder<StoryITN> 
     */
    open class func verifyBankAccountWithRequestBuilder(_id: String, profileId: String, verified: Bool? = nil) -> RequestBuilder<StoryITN> {
        var path = "/profiles/{profileId}/bankaccounts/{id}/verify"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let profileIdPreEscape = "\(profileId)"
        let profileIdPostEscape = profileIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{profileId}", with: profileIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "verified": verified
        ])

        let requestBuilder: RequestBuilder<StoryITN>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
