//
// PasportAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class PasportAPI {
    /**
     Скачивание изображения

     - parameter _id: (path)  
     - parameter page: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func downloadPasportPage(_id: String, page: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        downloadPasportPageWithRequestBuilder(_id: _id, page: page).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Скачивание изображения
     - GET /profiles/{id}/pasport/{page}/download

     - parameter _id: (path)  
     - parameter page: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func downloadPasportPageWithRequestBuilder(_id: String, page: Int) -> RequestBuilder<Void> {
        var path = "/profiles/{id}/pasport/{page}/download"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let pagePreEscape = "\(page)"
        let pagePostEscape = pagePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{page}", with: pagePostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Получение паспортных данных

     - parameter _id: (path) Уникальный идентификатор в формате StoryId 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getPasportById(_id: String, completion: @escaping ((_ data: StoryPasport?,_ error: Error?) -> Void)) {
        getPasportByIdWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Получение паспортных данных
     - GET /profiles/{id}/pasport

     - examples: [{contentType=application/json, example={
  "code" : "code",
  "pages" : [ {
    "size" : 0,
    "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
    "modifiedBy" : "modifiedBy",
    "mimeType" : "mimeType",
    "page" : 11
  }, {
    "size" : 0,
    "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
    "modifiedBy" : "modifiedBy",
    "mimeType" : "mimeType",
    "page" : 11
  } ],
  "profileId" : "profileId",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "issuedBy" : "issuedBy",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "modifiedBy" : "modifiedBy",
  "sn" : "sn",
  "issuedAt" : "2000-01-23T04:56:07.000+00:00",
  "verifiedBy" : "verifiedBy"
}}]
     - parameter _id: (path) Уникальный идентификатор в формате StoryId 

     - returns: RequestBuilder<StoryPasport> 
     */
    open class func getPasportByIdWithRequestBuilder(_id: String) -> RequestBuilder<StoryPasport> {
        var path = "/profiles/{id}/pasport"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryPasport>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Изменение паспортных данных

     - parameter _id: (path) Уникальный идентификатор в формате StoryId 
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func setPasport(_id: String, body: StoryPasportDTO? = nil, completion: @escaping ((_ data: StoryPasport?,_ error: Error?) -> Void)) {
        setPasportWithRequestBuilder(_id: _id, body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Изменение паспортных данных
     - PUT /profiles/{id}/pasport

     - examples: [{contentType=application/json, example={
  "code" : "code",
  "pages" : [ {
    "size" : 0,
    "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
    "modifiedBy" : "modifiedBy",
    "mimeType" : "mimeType",
    "page" : 11
  }, {
    "size" : 0,
    "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
    "modifiedBy" : "modifiedBy",
    "mimeType" : "mimeType",
    "page" : 11
  } ],
  "profileId" : "profileId",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "issuedBy" : "issuedBy",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "modifiedBy" : "modifiedBy",
  "sn" : "sn",
  "issuedAt" : "2000-01-23T04:56:07.000+00:00",
  "verifiedBy" : "verifiedBy"
}}]
     - parameter _id: (path) Уникальный идентификатор в формате StoryId 
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<StoryPasport> 
     */
    open class func setPasportWithRequestBuilder(_id: String, body: StoryPasportDTO? = nil) -> RequestBuilder<StoryPasport> {
        var path = "/profiles/{id}/pasport"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryPasport>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Загрузка изображения

     - parameter _id: (path)  
     - parameter page: (path)  
     - parameter contentType: (form)  (optional)
     - parameter contentDisposition: (form)  (optional)
     - parameter headers: (form)  (optional)
     - parameter length: (form)  (optional)
     - parameter name: (form)  (optional)
     - parameter fileName: (form)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func uploadPasportPage(_id: String, page: Int, contentType: String? = nil, contentDisposition: String? = nil, headers: [String:[String]]? = nil, length: Int64? = nil, name: String? = nil, fileName: String? = nil, completion: @escaping ((_ data: StoryITN?,_ error: Error?) -> Void)) {
        uploadPasportPageWithRequestBuilder(_id: _id, page: page, contentType: contentType, contentDisposition: contentDisposition, headers: headers, length: length, name: name, fileName: fileName).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Загрузка изображения
     - PUT /profiles/{id}/pasport/{page}/upload

     - examples: [{contentType=application/json, example={
  "itn" : "itn",
  "size" : 0,
  "profileId" : "profileId",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "modifiedBy" : "modifiedBy",
  "mimeType" : "mimeType",
  "verifiedBy" : "verifiedBy"
}}]
     - parameter _id: (path)  
     - parameter page: (path)  
     - parameter contentType: (form)  (optional)
     - parameter contentDisposition: (form)  (optional)
     - parameter headers: (form)  (optional)
     - parameter length: (form)  (optional)
     - parameter name: (form)  (optional)
     - parameter fileName: (form)  (optional)

     - returns: RequestBuilder<StoryITN> 
     */
    open class func uploadPasportPageWithRequestBuilder(_id: String, page: Int, contentType: String? = nil, contentDisposition: String? = nil, headers: [String:[String]]? = nil, length: Int64? = nil, name: String? = nil, fileName: String? = nil) -> RequestBuilder<StoryITN> {
        var path = "/profiles/{id}/pasport/{page}/upload"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let pagePreEscape = "\(page)"
        let pagePostEscape = pagePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{page}", with: pagePostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let formParams: [String:Any?] = [
                "ContentType": contentType,
                "ContentDisposition": contentDisposition,
                "Headers": headers,
                "Length": length?.encodeToJSON(),
                "Name": name,
                "FileName": fileName
        ]

        let nonNullParameters = APIHelper.rejectNil(formParams)
        let parameters = APIHelper.convertBoolToString(nonNullParameters)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryITN>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Подтверждение паспортных данных

     - parameter _id: (path) Уникальный идентификатор в формате StoryId 
     - parameter verified: (query)  (optional, default to false)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func verifyPasport(_id: String, verified: Bool? = nil, completion: @escaping ((_ data: StoryPasport?,_ error: Error?) -> Void)) {
        verifyPasportWithRequestBuilder(_id: _id, verified: verified).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Подтверждение паспортных данных
     - PUT /profiles/{id}/pasport/verify

     - examples: [{contentType=application/json, example={
  "code" : "code",
  "pages" : [ {
    "size" : 0,
    "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
    "modifiedBy" : "modifiedBy",
    "mimeType" : "mimeType",
    "page" : 11
  }, {
    "size" : 0,
    "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
    "modifiedBy" : "modifiedBy",
    "mimeType" : "mimeType",
    "page" : 11
  } ],
  "profileId" : "profileId",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "issuedBy" : "issuedBy",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "modifiedBy" : "modifiedBy",
  "sn" : "sn",
  "issuedAt" : "2000-01-23T04:56:07.000+00:00",
  "verifiedBy" : "verifiedBy"
}}]
     - parameter _id: (path) Уникальный идентификатор в формате StoryId 
     - parameter verified: (query)  (optional, default to false)

     - returns: RequestBuilder<StoryPasport> 
     */
    open class func verifyPasportWithRequestBuilder(_id: String, verified: Bool? = nil) -> RequestBuilder<StoryPasport> {
        var path = "/profiles/{id}/pasport/verify"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "verified": verified
        ])

        let requestBuilder: RequestBuilder<StoryPasport>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
