//
// ProfilePasportAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ProfilePasportAPI {
    /**
     Скачивание изображения страницы паспорта

     - parameter page: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func downloadPasportPage(page: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        downloadPasportPageWithRequestBuilder(page: page).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Скачивание изображения страницы паспорта
     - GET /profile/pasport/{page}/download

     - parameter page: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func downloadPasportPageWithRequestBuilder(page: Int) -> RequestBuilder<Void> {
        var path = "/profile/pasport/{page}/download"
        let pagePreEscape = "\(page)"
        let pagePostEscape = pagePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{page}", with: pagePostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Получение паспортных данных текущего пользователя

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getPasport(completion: @escaping ((_ data: StoryPasport?,_ error: Error?) -> Void)) {
        getPasportWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Получение паспортных данных текущего пользователя
     - GET /profile/pasport

     - examples: [{contentType=application/json, example={
  "code" : "code",
  "pages" : [ {
    "size" : 0,
    "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
    "modifiedBy" : "modifiedBy",
    "mimeType" : "mimeType",
    "page" : 11
  }, {
    "size" : 0,
    "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
    "modifiedBy" : "modifiedBy",
    "mimeType" : "mimeType",
    "page" : 11
  } ],
  "profileId" : "profileId",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "issuedBy" : "issuedBy",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "modifiedBy" : "modifiedBy",
  "sn" : "sn",
  "issuedAt" : "2000-01-23T04:56:07.000+00:00",
  "verifiedBy" : "verifiedBy"
}}]

     - returns: RequestBuilder<StoryPasport> 
     */
    open class func getPasportWithRequestBuilder() -> RequestBuilder<StoryPasport> {
        let path = "/profile/pasport"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryPasport>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Удаление изображения страницы паспорта

     - parameter page: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func removePasportPageBlob(page: Int, completion: @escaping ((_ data: StoryITN?,_ error: Error?) -> Void)) {
        removePasportPageBlobWithRequestBuilder(page: page).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Удаление изображения страницы паспорта
     - DELETE /profile/pasport/{page}/upload

     - examples: [{contentType=application/json, example={
  "itn" : "itn",
  "size" : 0,
  "profileId" : "profileId",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "modifiedBy" : "modifiedBy",
  "mimeType" : "mimeType",
  "verifiedBy" : "verifiedBy"
}}]
     - parameter page: (path)  

     - returns: RequestBuilder<StoryITN> 
     */
    open class func removePasportPageBlobWithRequestBuilder(page: Int) -> RequestBuilder<StoryITN> {
        var path = "/profile/pasport/{page}/upload"
        let pagePreEscape = "\(page)"
        let pagePostEscape = pagePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{page}", with: pagePostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryITN>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Изменение паспортных данных текущего пользователя

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func setPasport(body: StoryPasportDTO? = nil, completion: @escaping ((_ data: StoryPasport?,_ error: Error?) -> Void)) {
        setPasportWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Изменение паспортных данных текущего пользователя
     - PUT /profile/pasport

     - examples: [{contentType=application/json, example={
  "code" : "code",
  "pages" : [ {
    "size" : 0,
    "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
    "modifiedBy" : "modifiedBy",
    "mimeType" : "mimeType",
    "page" : 11
  }, {
    "size" : 0,
    "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
    "modifiedBy" : "modifiedBy",
    "mimeType" : "mimeType",
    "page" : 11
  } ],
  "profileId" : "profileId",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "issuedBy" : "issuedBy",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "modifiedBy" : "modifiedBy",
  "sn" : "sn",
  "issuedAt" : "2000-01-23T04:56:07.000+00:00",
  "verifiedBy" : "verifiedBy"
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<StoryPasport> 
     */
    open class func setPasportWithRequestBuilder(body: StoryPasportDTO? = nil) -> RequestBuilder<StoryPasport> {
        let path = "/profile/pasport"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryPasport>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Загрузка изображения страницы паспорта

     - parameter page: (path)  
     - parameter contentType: (form)  (optional)
     - parameter contentDisposition: (form)  (optional)
     - parameter headers: (form)  (optional)
     - parameter length: (form)  (optional)
     - parameter name: (form)  (optional)
     - parameter fileName: (form)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func uploadPasportPage(page: Int, contentType: String? = nil, contentDisposition: String? = nil, headers: [String:[String]]? = nil, length: Int64? = nil, name: String? = nil, fileName: String? = nil, completion: @escaping ((_ data: StoryITN?,_ error: Error?) -> Void)) {
        uploadPasportPageWithRequestBuilder(page: page, contentType: contentType, contentDisposition: contentDisposition, headers: headers, length: length, name: name, fileName: fileName).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Загрузка изображения страницы паспорта
     - PUT /profile/pasport/{page}/upload

     - examples: [{contentType=application/json, example={
  "itn" : "itn",
  "size" : 0,
  "profileId" : "profileId",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "modifiedBy" : "modifiedBy",
  "mimeType" : "mimeType",
  "verifiedBy" : "verifiedBy"
}}]
     - parameter page: (path)  
     - parameter contentType: (form)  (optional)
     - parameter contentDisposition: (form)  (optional)
     - parameter headers: (form)  (optional)
     - parameter length: (form)  (optional)
     - parameter name: (form)  (optional)
     - parameter fileName: (form)  (optional)

     - returns: RequestBuilder<StoryITN> 
     */
    open class func uploadPasportPageWithRequestBuilder(page: Int, contentType: String? = nil, contentDisposition: String? = nil, headers: [String:[String]]? = nil, length: Int64? = nil, name: String? = nil, fileName: String? = nil) -> RequestBuilder<StoryITN> {
        var path = "/profile/pasport/{page}/upload"
        let pagePreEscape = "\(page)"
        let pagePostEscape = pagePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{page}", with: pagePostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let formParams: [String:Any?] = [
                "ContentType": contentType,
                "ContentDisposition": contentDisposition,
                "Headers": headers,
                "Length": length?.encodeToJSON(),
                "Name": name,
                "FileName": fileName
        ]

        let nonNullParameters = APIHelper.rejectNil(formParams)
        let parameters = APIHelper.convertBoolToString(nonNullParameters)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryITN>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
