//
// ProfileDemographicsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ProfileDemographicsAPI {
    /**
     Получение личных данных

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getDemographics(completion: @escaping ((_ data: StoryDemographics?,_ error: Error?) -> Void)) {
        getDemographicsWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Получение личных данных
     - GET /profile/demographics

     - examples: [{contentType=application/json, example={
  "birthday" : "2000-01-23T04:56:07.000+00:00",
  "patronymic" : "patronymic",
  "gender" : true,
  "profileId" : "profileId",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "surname" : "surname",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "name" : "name",
  "modifiedBy" : "modifiedBy",
  "verifiedBy" : "verifiedBy"
}}]

     - returns: RequestBuilder<StoryDemographics> 
     */
    open class func getDemographicsWithRequestBuilder() -> RequestBuilder<StoryDemographics> {
        let path = "/profile/demographics"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryDemographics>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Изменение личных данных

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateDemographics(body: StoryDemographicsDTO? = nil, completion: @escaping ((_ data: StoryDemographics?,_ error: Error?) -> Void)) {
        updateDemographicsWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Изменение личных данных
     - PUT /profile/demographics

     - examples: [{contentType=application/json, example={
  "birthday" : "2000-01-23T04:56:07.000+00:00",
  "patronymic" : "patronymic",
  "gender" : true,
  "profileId" : "profileId",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "surname" : "surname",
  "verified" : true,
  "verifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "name" : "name",
  "modifiedBy" : "modifiedBy",
  "verifiedBy" : "verifiedBy"
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<StoryDemographics> 
     */
    open class func updateDemographicsWithRequestBuilder(body: StoryDemographicsDTO? = nil) -> RequestBuilder<StoryDemographics> {
        let path = "/profile/demographics"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryDemographics>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
