//
// ProfileAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ProfileAPI {
    /**
     Получение профиля текущего пользователя

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getProfile(completion: @escaping ((_ data: StoryProfile?,_ error: Error?) -> Void)) {
        getProfileWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Получение профиля текущего пользователя
     - GET /Profile

     - examples: [{contentType=application/json, example={
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "emailVerified" : true,
  "createdBy" : "createdBy",
  "phone" : "phone",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "phoneVerified" : true,
  "modifiedBy" : "modifiedBy",
  "id" : "id",
  "email" : "email",
  "username" : "username"
}}]

     - returns: RequestBuilder<StoryProfile> 
     */
    open class func getProfileWithRequestBuilder() -> RequestBuilder<StoryProfile> {
        let path = "/Profile"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryProfile>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Обновление текущего профиля

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateProfile(body: StoryProfileDTO? = nil, completion: @escaping ((_ data: StoryProfile?,_ error: Error?) -> Void)) {
        updateProfileWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Обновление текущего профиля
     - PUT /Profile

     - examples: [{contentType=application/json, example={
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "emailVerified" : true,
  "createdBy" : "createdBy",
  "phone" : "phone",
  "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
  "phoneVerified" : true,
  "modifiedBy" : "modifiedBy",
  "id" : "id",
  "email" : "email",
  "username" : "username"
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<StoryProfile> 
     */
    open class func updateProfileWithRequestBuilder(body: StoryProfileDTO? = nil) -> RequestBuilder<StoryProfile> {
        let path = "/Profile"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<StoryProfile>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
